development:
  bucket: cineforumdevelopment
  access_key_id: AKIAIUJHH4FU6HYO5K7Q
  secret_access_key: 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

test:
  bucket: cineforumtest
  access_key_id: AKIAIUJHH4FU6HYO5K7Q
  secret_access_key: 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

production:
  bucket: cineforum
  access_key_id: AKIAIUJHH4FU6HYO5K7Q
  secret_access_key: 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

